# Compare classification methods for identifying org. science perspectives in JSTOR articles
## Using balanced samples from hand-labeled set of articles

@author: Jaren Haber, PhD<br>
@coauthors: Prof. Heather Haveman, UC Berkeley; Yoon Sung Hong, Wayfair<br>
@contact: Jaren.Haber@georgetown.edu<br>
@project: Computational Literature Review of Organizational Scholarship<br>
@date: December 2020

'''
Trains classifiers to predict whether an article is about a given perspective in org. science. To train the classifiers, uses preliminary labeled articles, broken down as follows: 
Cultural: 105 yes, 209 no
Relational: 92 yes, 230 no
Demographic: 77 yes, 249 no
Compares f1_weighted scores of four model structures using 10-Fold Cross Validation: Logistic regression, SVM, Naive Bayes, and Decision Tree. Oversamples training data to .7 (7:10 minority:majority class).
'''

## Initialize

In [1]:
######################################################
# Import libraries
######################################################

import pandas as pd
import numpy as np
import re
from collections import Counter
from datetime import date
import os

import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')

stemmer = WordNetLemmatizer()

from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt

import joblib
import csv

from sklearn.datasets import load_files
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, cross_val_predict, train_test_split, KFold

# !pip install imblearn
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

import sys; sys.path.insert(0, "../preprocess/") # For loading functions from files in other directory
from quickpickle import quickpickle_dump, quickpickle_load # custom scripts for quick saving & loading to pickle format

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
######################################################
# Define filepaths
######################################################

thisday = date.today().strftime("%m%d%y")

cwd = os.getcwd()
root = str.replace(cwd, 'classification/modeling', '')

# Directory for prepared data and trained models: save files here
data_fp = root + 'classification/data/'
model_fp = root + 'classification/models/'

# Current article lists
article_list_fp = data_fp + 'filtered_length_index.csv' # Filtered index of research articles
article_paths_fp = data_fp + 'filtered_length_article_paths.csv' # List of article file paths

# Preprocessed training data
cult_labeled_fp = data_fp + 'training_cultural_preprocessed_121520.pkl'
relt_labeled_fp = data_fp + 'training_relational_preprocessed_121520.pkl'
demog_labeled_fp = data_fp + 'training_demographic_preprocessed_121520.pkl'

# Model filepaths
cult_model_fp = model_fp + f'classifier_cult_{str(thisday)}.joblib'
relt_model_fp = model_fp + f'classifier_relt_{str(thisday)}.joblib'
demog_model_fp = model_fp + f'classifier_demog_{str(thisday)}.joblib'

# Vectorizers trained on hand-coded data (use to limit vocab of input texts)
cult_vec_fp = model_fp + 'vectorizer_cult_121520.joblib'
relt_vec_fp = model_fp + 'vectorizer_relt_121520.joblib'
demog_vec_fp = model_fp + 'vectorizer_demog_121520.joblib'

## Load & inspect data

In [3]:
cult_df = quickpickle_load(cult_labeled_fp)
relt_df = quickpickle_load(relt_labeled_fp)
demog_df = quickpickle_load(demog_labeled_fp)

cult_df.head(10)

text  cultural_score
0  [[journal, of, managerial, issues, vol, xxiii,...             1.0
1  [[organization, ht, icna, vol, no, may, june, ...             1.0
2  [[from, fiefs, to, clans, and, network, capita...             1.0
3  [[the, collective, strategy, framework, an, ap...             1.0
4  [[manag, int, rev, doi, sl, research, article,...             1.0
5  [[int, studies, ofmgt, amp, org, vol, no, pp, ...             1.0
6  [[linking, organizational, values, to, relatio...             1.0
7  [[journal, of, organizational, behavior, organ...             1.0
8  [[®, academy, oí, management, learning, amp, e...             1.0
9  [[strategie, management, journal, strat, mgmt,...             1.0

In [4]:
# Check score distribution across classes
print(cult_df.groupby('cultural_score').size())
print()
print(relt_df.groupby('relational_score').size())
print()
print(demog_df.groupby('demographic_score').size())

cultural_score
0.0    209
0.5     12
1.0    112
dtype: int64

relational_score
0.0    229
0.5      7
1.0    104
dtype: int64

demographic_score
0.0    248
0.5      5
1.0     91
dtype: int64


In [5]:
# Drop unsure cases: where X_score = 0.5
drop_unsure = True

if drop_unsure:
    cult_df_yes = cult_df[cult_df['cultural_score'] == 1.0]
    cult_df_no = cult_df[cult_df['cultural_score'] == 0.0]
    cult_df = pd.concat([cult_df_yes, cult_df_no])
    
    relt_df_yes = relt_df[relt_df['relational_score'] == 1.0]
    relt_df_no = relt_df[relt_df['relational_score'] == 0.0]
    relt_df = pd.concat([relt_df_yes, relt_df_no])
    
    demog_df_yes = demog_df[demog_df['demographic_score'] == 1.0]
    demog_df_no = demog_df[demog_df['demographic_score'] == 0.0]
    demog_df = pd.concat([demog_df_yes, demog_df_no])

### Check vocab size and frequent words

In [6]:
def collect_article_tokens(article, return_string=False):
    '''
    Collects words from already-tokenized sentences representing each article.
    
    Args:
        article: list of lists of words (each list is a sentence)
        return_string: whether to return single, long string representing article
    Returns:
        tokens: string if return_string, else list of tokens
    '''
    
    tokens = [] # initialize
    
    if return_string:
        for sent in article:
            sent = ' '.join(sent) # make sentence into a string
            tokens.append(sent) # add sentence to list of sentences
        tokens = ' '.join(tokens) # join sentences into string
        return tokens # return string
    
    else:
        for sent in article:
            tokens += [word for word in sent] # add each word to list of tokens
        return tokens # return list of tokens

# For capturing word frequencies, add all words from each article to single, shared list (can't use this to create models)
cult_tokens = []; cult_df['text'].apply(lambda article: cult_tokens.extend([word for word in collect_article_tokens(article)]))
relt_tokens = []; relt_df['text'].apply(lambda article: relt_tokens.extend([word for word in collect_article_tokens(article)]))
demog_tokens = []; demog_df['text'].apply(lambda article: demog_tokens.extend([word for word in collect_article_tokens(article)]))
print()

In [7]:
# Look at size of vocabulary and most frequent words
tokens = (cult_tokens + relt_tokens) + demog_tokens
print('Vocab size:', len(set(tokens)))
print()

# Check out most frequent words in labeled texts
freq = Counter(tokens)
print('20 most frequent words in labeled articles:')
freq.most_common(20)

Vocab size: 77175

20 most frequent words in labeled articles:


[('the', 565409),
 ('of', 405009),
 ('and', 311316),
 ('in', 219162),
 ('to', 206031),
 ('that', 111131),
 ('is', 98751),
 ('for', 89030),
 ('as', 72639),
 ('on', 59905),
 ('are', 59644),
 ('with', 55565),
 ('by', 53782),
 ('this', 51108),
 ('be', 45031),
 ('oasis', 40297),
 ('or', 40225),
 ('it', 38114),
 ('from', 37627),
 ('an', 36967)]

### Check frequent sentences (to improve cleaning)

In [8]:
# Add sentences from each article to empty list:
cult_sents = []; cult_df['text'].apply(
    lambda article: cult_sents.extend(
        [' '.join([word for word in sent]) for sent in article]))
relt_sents = []; relt_df['text'].apply(
    lambda article: relt_sents.extend(
        [' '.join([word for word in sent]) for sent in article]))
demog_sents = []; demog_df['text'].apply(
    lambda article: demog_sents.extend(
        [' '.join([word for word in sent]) for sent in article]))

sents = (cult_sents + relt_sents) + demog_sents
print('Number of sentences:', len(sents))
print()

# Check out most frequent sentences in labeled texts
freq = Counter(sents)
print('20 most frequent sentences in labeled articles:')
freq.most_common(20)

Number of sentences: 112092

20 most frequent sentences in labeled articles:


[('colsep', 9668),
 ('rowsep', 9662),
 ('oasis entry colname', 9297),
 ('char', 5966),
 ('align char', 5887),
 ('valign bottom oasis entry', 5674),
 ('oasis row', 5194),
 ('align center', 2425),
 ('valign bottom', 2011),
 ('oasis entry colname colsep rowsep align char char oasis entry', 1589),
 ('oasis entry colname colsep rowsep align char char', 1249),
 ('align left', 1205),
 ('oasis entry colsep rowsep valign bottom oasis entry', 1045),
 ('label label', 647),
 ('fn', 639),
 ('oasis entry colsep rowsep oasis entry', 531),
 ('sec', 503),
 ('sec id sc', 467),
 ('oasis entry colsep rowsep valign bottom', 462),
 ('oasis entry colsep rowsep', 440)]

### Load and apply text vectorizers

In [9]:
# Collect articles: Add each article as single str to list of str:
cult_docs = [] # empty list
cult_df['text'].apply(
    lambda article: cult_docs.append(
        collect_article_tokens(
            article, 
            return_string=True)))

relt_docs = [] # empty list
relt_df['text'].apply(
    lambda article: relt_docs.append(
       collect_article_tokens(
            article, 
            return_string=True)))

demog_docs = [] # empty list
demog_df['text'].apply(
    lambda article: demog_docs.append(
        collect_article_tokens(
            article, 
            return_string=True)))

print() # skip weird output

In [11]:
# Define stopwords used by JSTOR
jstor_stopwords = set(["a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "into", "is", "it", "no", "not", "of", "on", "or", "such", "that", "the", "their", "then", "there", "these", "they", "this", "to", "was", "will", "with"])

# Uses TFIDF weighted DTM because results in better classifier accuracy than unweighted
cult_vectorizer = joblib.load(cult_vec_fp, "r+")
X_cult = cult_vectorizer.transform(cult_docs)
print('Number of features in cultural vectorizer:', len(cult_vectorizer.get_feature_names()))
print(cult_vectorizer.get_feature_names()[::1000]) # get every 1000th word
print()

relt_vectorizer = joblib.load(relt_vec_fp, "r+")
X_relt = relt_vectorizer.transform(relt_docs)
print('Number of features in relational vectorizer:', len(relt_vectorizer.get_feature_names()))
print(relt_vectorizer.get_feature_names()[::1000]) # get every 1000th word
print()

demog_vectorizer = joblib.load(demog_vec_fp, "r+")
X_demog = demog_vectorizer.transform(demog_docs)
print('Number of features in demographic vectorizer:', len(demog_vectorizer.get_feature_names()))
print(demog_vectorizer.get_feature_names()[::1000]) # get every 1000th word

Number of features in cultural vectorizer: 64012
['aa', 'affirming', 'anatole', 'armored', 'axirk', 'benefactors', 'bolton', 'burgher', 'cavan', 'circumference', 'comminity', 'contagious', 'criado', 'debating', 'desk', 'dislodging', 'dsscordant', 'eligibles', 'equality', 'expectan', 'fetch', 'former', 'gaston', 'goudszwaard', 'handler', 'hile', 'hypocrits', 'including', 'insurance', 'isms', 'jw', 'kouzmin', 'legalizing', 'loewenberg', 'malinis', 'mde', 'ministries', 'msr', 'nelder', 'noon', 'oman', 'overgrazed', 'pear', 'pjs', 'practicecomment', 'promulgation', 'race', 'reducible', 'resellers', 'rockstuhl', 'satan', 'selma', 'siglo', 'solo', 'steakhouse', 'sued', 'tampered', 'thirteenth', 'traits', 'ucx', 'unquestioned', 'vertinsky', 'weighed', 'wu', 'ров']

Number of features in relational vectorizer: 64175
['aa', 'affront', 'ancovas', 'arraying', 'baan', 'benschoten', 'boomers', 'businesscasecsr', 'ceived', 'cjxi', 'comparativa', 'contradistinction', 'crucifixion', 'decreasingpi', 'd

## Setup for modeling

In [12]:
######################################################
# Balance x_train, y_train
######################################################

def resample_data(X_train, Y_train, undersample = False, sampling_ratio = 1.0):
    """
    Args:
        X_train: X training data
        Y_train: Y training data
        undersample: boolean for over or undersampling
        sampling_ratio: ratio of minority to majority class
        
        archived/not used:
        sampling_strategy: strategy for resampled distribution
            if oversample: 'majority' makes minority = to majority
            if undersample: 'minority' makes majority = to minority
            
    Returns:
        X_balanced: predictors at balanced ratio
        Y_balanced: outcomes at balanced ratio
    """
    
    if undersample == True:
        undersample = RandomUnderSampler(sampling_strategy=sampling_ratio)
        X_balanced, Y_balanced = undersample.fit_resample(X_train, Y_train)
    else:
        oversample = RandomOverSampler(sampling_strategy=sampling_ratio)
        X_balanced, Y_balanced = oversample.fit_resample(X_train, Y_train)
    
    print(f'Y_train: {Counter(Y_train)}\nY_resample: {Counter(Y_balanced)}')
    
    return X_balanced, Y_balanced

In [13]:
######################################################
# k-fold cross validation for model evaluation
######################################################

# Define test options for k-fold CV
num_folds = 10 
seed = 3
scoring='f1_weighted' # set scoring metric (not used here)

def show_kfold_output(models, 
                      X, 
                      Y, 
                      num_folds = num_folds, 
                      random_state = seed, 
                      shuffle = True):
    '''
    Estimates the accuracy of different model algorithms, adds results to a results array and returns.
    Prints the accuracy results: averages and std.
    Uses cross_val_predict, which unlike cross_val_score cannot define scoring option/evaluation metric.
    
    Args:
        models: list of (name, model) tuples
        X: predictors
        Y: outcomes
        num_folds: Split data randomly into num_folds parts: (num_folds-1) for training, 1 for scoring
        random_state: seed
        shuffle: 
    
    Returns:
        results: list of model results
        names: list of model names (matches results)
        
    Source: 
        https://stackoverflow.com/questions/40057049/using-confusion-matrix-as-scoring-metric-in-cross-validation-in-scikit-learn
    '''
    
    results = []
    names = []
    
    for name, model in models:
        # Setup model options
        kfold = KFold(
            n_splits=num_folds, 
            random_state=seed, 
            shuffle=True)
        
        # Get kfold results
        cv_results = cross_val_predict(
            model, 
            X, 
            Y, 
            cv=kfold, 
            #scoring=scoring, 
            n_jobs=-1) # use all cores = faster
        
        # Add results and name of each algorithm to the model array
        results.append(cv_results)
        names.append(name)
        
        # Print results
        print(f'{name}:')
        print()
        print(f'Mean (std):\t {round(cv_results.mean(),4)} ({round(cv_results.std(),4)})')
        print(f'Accuracy:\t', {round(accuracy_score(Y_balanced, cv_results)), 4})
        print()
        print('Confusion matrix:\n', confusion_matrix(Y_balanced, cv_results))
        print()
        print('Report:\n', classification_report(Y_balanced, cv_results))
        print()
        
    # Return arrays
    return results, names

## Evaluate algorithms: Cultural perspective

In [14]:
######################################################
# Prepare training and validation data
######################################################

# Separate training and final validation data set. First remove class
# label from data (X). Setup target class (Y)
# Then make the validation set 10% of the entire
# set of labeled data (X_validate, Y_validate)

cult_df = cult_df[['text', 'cultural_score']]
print("Number of cases:", str(X_cult.shape[0]))

valueArray = cult_df.values
Y = valueArray[:,1]
Y = Y.astype('float')
print("Number of codes (should match):", str(len(Y)))

test_size = 0.2
seed = 3
X_train, X_validate, Y_train, Y_validate = train_test_split(
    X_cult, 
    Y, 
    test_size=test_size, 
    random_state=seed)

print(f'Y_train Distribution: {Counter(Y_train).most_common()}')

Number of cases: 321
Number of codes (should match): 321
Y_train Distribution: [(0.0, 167), (1.0, 89)]


In [15]:
######################################################
# Oversample to desirable ratio
######################################################

# Use these settings here and below
sampling_ratio = 1.0 # ratio of minority to majority cases
undersample = False # whether to undersample or oversample

X_balanced, Y_balanced = resample_data(
    X_cult, 
    Y, 
    undersample=undersample, 
    sampling_ratio=sampling_ratio)

Y_train: Counter({0.0: 209, 1.0: 112})
Y_resample: Counter({1.0: 209, 0.0: 209})


In [16]:
######################################################
# Use different algorithms to build models
######################################################

models = []
models.append(('K-Nearest Neighbors (KNN)', KNeighborsClassifier()))
models.append(('Random Forest (RF)', RandomForestClassifier(random_state=seed)))
models.append(('Decision Tree (DT)', DecisionTreeClassifier(random_state=seed)))
models.append(('Multinomial Naive Bayes (MNB)', MultinomialNB()))
models.append(('Logistic Regression (LR)', LogisticRegression(random_state=seed)))
models.append(('Support Vector Machine (SVM)', SVC(gamma='auto')))

# Evaluate algorithms using 10-fold cross validation
results, names = show_kfold_output(models=models, 
                                   X=X_balanced, 
                                   Y=Y_balanced)

K-Nearest Neighbors (KNN):

Mean (std):	 0.6388 (0.4804)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[139  70]
 [ 12 197]]

Report:
               precision    recall  f1-score   support

         0.0       0.92      0.67      0.77       209
         1.0       0.74      0.94      0.83       209

    accuracy                           0.80       418
   macro avg       0.83      0.80      0.80       418
weighted avg       0.83      0.80      0.80       418


Random Forest (RF):

Mean (std):	 0.4641 (0.4987)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[201   8]
 [ 23 186]]

Report:
               precision    recall  f1-score   support

         0.0       0.90      0.96      0.93       209
         1.0       0.96      0.89      0.92       209

    accuracy                           0.93       418
   macro avg       0.93      0.93      0.93       418
weighted avg       0.93      0.93      0.93       418


Decision Tree (DT):

Mean (std):	 0.5359 (0.4987)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [

In [17]:
######################################################
# Save best model
######################################################

rf_cult = RandomForestClassifier(random_state=seed).fit(X_balanced, Y_balanced)
joblib.dump(rf_cult, cult_model_fp)

['/home/jovyan/work/classification/models/classifier_cult_121520.joblib']

## Evaluate algorithms: Relational perspective

In [18]:
######################################################
# Prepare training and validation data
######################################################

# Separate training and final validation data set. First remove class
# label from data (X). Setup target class (Y)
# Then make the validation set 10% of the entire
# set of labeled data (X_validate, Y_validate)

relt_df = relt_df[['text', 'relational_score']]
print("Number of cases:", str(X_relt.shape[0]))

valueArray = relt_df.values
Y = valueArray[:,1]
Y = Y.astype('float')
print("Number of codes (should match):", str(len(Y)))

test_size = 0.2
seed = 3
X_train, X_validate, Y_train, Y_validate = train_test_split(X_relt, Y, test_size=test_size, random_state=seed)

print(f'Y_train Distribution: {Counter(Y_train).most_common()}')

Number of cases: 333
Number of codes (should match): 333
Y_train Distribution: [(0.0, 183), (1.0, 83)]


In [19]:
######################################################
# Oversample to desirable ratio
######################################################

X_balanced, Y_balanced = resample_data(
    X_relt, Y, 
    undersample=undersample, 
    sampling_ratio=sampling_ratio)

Y_train: Counter({0.0: 229, 1.0: 104})
Y_resample: Counter({1.0: 229, 0.0: 229})


In [20]:
######################################################
# Use different algorithms to build models
######################################################

models = []
models.append(('K-Nearest Neighbors (KNN)', KNeighborsClassifier()))
models.append(('Random Forest (RF)', RandomForestClassifier(random_state=seed)))
models.append(('Decision Tree (DT)', DecisionTreeClassifier(random_state=seed)))
models.append(('Multinomial Naive Bayes (MNB)', MultinomialNB()))
models.append(('Logistic Regression (LR)', LogisticRegression(random_state=seed)))
models.append(('Support Vector Machine (SVM)', SVC(gamma='auto')))

# Evaluate algorithms using 10-fold cross validation
results, names = show_kfold_output(models=models, 
                                   X=X_balanced, 
                                   Y=Y_balanced)

K-Nearest Neighbors (KNN):

Mean (std):	 0.7074 (0.4549)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[129 100]
 [  5 224]]

Report:
               precision    recall  f1-score   support

         0.0       0.96      0.56      0.71       229
         1.0       0.69      0.98      0.81       229

    accuracy                           0.77       458
   macro avg       0.83      0.77      0.76       458
weighted avg       0.83      0.77      0.76       458


Random Forest (RF):

Mean (std):	 0.5022 (0.5)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[223   6]
 [  5 224]]

Report:
               precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       229
         1.0       0.97      0.98      0.98       229

    accuracy                           0.98       458
   macro avg       0.98      0.98      0.98       458
weighted avg       0.98      0.98      0.98       458


Decision Tree (DT):

Mean (std):	 0.5306 (0.4991)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[20

In [21]:
######################################################
# Save best model
######################################################

rf_relt = RandomForestClassifier(random_state=seed).fit(X_balanced, Y_balanced)
joblib.dump(rf_relt, relt_model_fp)

['/home/jovyan/work/classification/models/classifier_relt_121520.joblib']

## Evaluate algorithms: Demographic perspective

In [22]:
######################################################
# Prepare training and validation data
######################################################

# Separate training and final validation data set. First reltove class
# label from data (X). Setup target class (Y)
# Then make the validation set 10% of the entire
# set of labeled data (X_validate, Y_validate)

demog_df = demog_df[['text', 'demographic_score']]
print("Number of cases:", str(X_demog.shape[0]))

valueArray = demog_df.values
Y = valueArray[:,1]
Y = Y.astype('float')
print("Number of codes (should match):", str(len(Y)))

test_size = 0.2
seed = 3
X_train, X_validate, Y_train, Y_validate = train_test_split(X_demog, Y, test_size=test_size, random_state=seed)

print(f'Y_train Distribution: {Counter(Y_train).most_common()}')

Number of cases: 339
Number of codes (should match): 339
Y_train Distribution: [(0.0, 199), (1.0, 72)]


In [23]:
######################################################
# Oversample to desirable ratio
######################################################

X_balanced, Y_balanced = resample_data(
    X_demog, Y, 
    undersample=undersample, 
    sampling_ratio=sampling_ratio)

Y_train: Counter({0.0: 248, 1.0: 91})
Y_resample: Counter({1.0: 248, 0.0: 248})


In [24]:
######################################################
# Use different algorithms to build models
######################################################

models = []
models.append(('K-Nearest Neighbors (KNN)', KNeighborsClassifier()))
models.append(('Random Forest (RF)', RandomForestClassifier(random_state=seed)))
models.append(('Decision Tree (DT)', DecisionTreeClassifier(random_state=seed)))
models.append(('Multinomial Naive Bayes (MNB)', MultinomialNB()))
models.append(('Logistic Regression (LR)', LogisticRegression(random_state=seed)))
models.append(('Support Vector Machine (SVM)', SVC(gamma='auto')))

# Evaluate algorithms using 10-fold cross validation
results, names = show_kfold_output(models=models, 
                                   X=X_balanced, 
                                   Y=Y_balanced)

K-Nearest Neighbors (KNN):

Mean (std):	 0.6552 (0.4753)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[169  79]
 [  2 246]]

Report:
               precision    recall  f1-score   support

         0.0       0.99      0.68      0.81       248
         1.0       0.76      0.99      0.86       248

    accuracy                           0.84       496
   macro avg       0.87      0.84      0.83       496
weighted avg       0.87      0.84      0.83       496


Random Forest (RF):

Mean (std):	 0.5101 (0.4999)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [[242   6]
 [  1 247]]

Report:
               precision    recall  f1-score   support

         0.0       1.00      0.98      0.99       248
         1.0       0.98      1.00      0.99       248

    accuracy                           0.99       496
   macro avg       0.99      0.99      0.99       496
weighted avg       0.99      0.99      0.99       496


Decision Tree (DT):

Mean (std):	 0.5403 (0.4984)
Accuracy:	 {1.0, 4}

Confusion matrix:
 [

In [25]:
######################################################
# Save best model
######################################################

rf_demog = RandomForestClassifier(random_state=seed).fit(X_balanced, Y_balanced)
joblib.dump(rf_demog, demog_model_fp)

['/home/jovyan/work/classification/models/classifier_demog_121520.joblib']